Декоративные элементы на главной странице
htmlacademy-htmlcss/142152-sedona-32 pull request #10
Opened 2021-11-06 19:13 UTC by DaryaNikolaeva31

2021-11-09 21:13 UTC, DaryaNikolaeva31 commented
Вроде получилось поправить главную
но сломался каталог)
сейчас буду править

Из того, что я вижу на главной: 

1. Не работают состояния на блоке .navigation-user, соц сетях и логотипа разработчика
2. В блоке "Подпишитесь на рассылку" placeholder зеркалится у меня, я понимаю, что это из-за transform: matrix, но как исправить- не понимаю
3. Pixel Perfect пока не пробовала, но уверена, будет миллион косяков

2021-11-10 19:56 UTC, wrgraff requested changes

2021-11-10 19:56 UTC, wrgraff commented on css/styles.css
> +.field:invalid {
Поисследуй [:placeholder-shown](https://doka.guide/css/placeholder-shown/), он поможет спрятать состояние ошибки до момента, пока в поле ничего не введено

2021-11-10 19:56 UTC, wrgraff commented on css/styles.css
> +  outline: 2px solid #ff5757;
2 пикселя — это кажется при фокусе состояние

2021-11-10 19:56 UTC, wrgraff commented on css/styles.css
> +  border: 3px solid #83b3d3;
Фокус через `border` приводит к сдвиганию блоков. Поэтому мы используем `outline`

2021-11-10 19:56 UTC, wrgraff commented on css/styles.css
> +  border: 3px solid #83b3d3;
При нажатии нет же рамки

2021-11-10 19:56 UTC, wrgraff commented on css/styles.css
> +}
Вот кстати именно здесь при фокусе подсвечивается border, а не outline.
Или можно попробовать добиться эффекта через отрицательный `outline-offset`

2021-11-10 19:56 UTC, wrgraff commented on css/styles.css
> +  border-radius: 4px;
А зачем при каждом состоянии указывать скругление, которое еще со статичного элемента работает?

2021-11-10 19:56 UTC, wrgraff commented on css/styles.css
> +  padding: 0;
Все повторяющиеся стили можно задать классу `.rating-stars`

2021-11-10 19:56 UTC, wrgraff commented on css/styles.css
> +  background-size: 18px 17px;
Ты можешь сделать так:

```suggestion
  background-size: 25px 17px;
```

Это сработает, если у тебя есть viewbox в иконке. Он не позволит `svg` исказиться, а лишнее расстояние как раз создаст пробелы между звездами.

Кроме этого есть еще и значение `space` у `background-repeat`. Можно с ним поработать, но скорее всего точности добиться не выйдет

2021-11-10 19:56 UTC, wrgraff commented on css/styles.css
> +.button-booking:hover {
По идее, изменения цвета должны пойти от цветных кнопок вроде `.button-brown`.
Разве не все кнопки одного цвета одинаково меняют цвет при состояниях и фокусе?

2021-11-11 10:01 UTC, DaryaNikolaeva31 commented on index.html
> +            <a class="navigation-link navigation-link-current" href="index.html">Главная</a>
удалила

2021-11-11 10:26 UTC, DaryaNikolaeva31 commented on index.html
> +        <img class="main-screen-picture-end" src="img/divider.svg">
cделала псевдоэлементом
в фон не получилось(

2021-11-11 10:28 UTC, DaryaNikolaeva31 commented on index.html
> +              <li class="services-item services-item-souvenirs">
hooray!

2021-11-11 10:31 UTC, DaryaNikolaeva31 commented on catalog.html
> +                </svg>
не поняла, что ты имеешь ввиду, в смысле, что мне здесь исправлять?

2021-11-11 10:36 UTC, DaryaNikolaeva31 commented on catalog.html
> +              <span class="rating-field">Рейтинг: 8,5</span>
заменила на box

2021-11-11 10:43 UTC, DaryaNikolaeva31 commented on css/styles.css
> +}
поняла
удалила

2021-11-11 10:46 UTC, DaryaNikolaeva31 commented on css/styles.css
> +.navigation-button:hover .navigation-user {
заменила на button-brown

2021-11-11 10:47 UTC, DaryaNikolaeva31 commented on css/styles.css
> +.navigation-button:focus .navigation-user {
лево право иногда путаю)
исправила

2021-11-11 10:51 UTC, DaryaNikolaeva31 commented on css/styles.css
> +}
и правда!исправила

2021-11-11 10:52 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  border: 3px solid #83b3d3;
исправила

2021-11-11 10:54 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  border: 3px solid #83b3d3;
исправила

2021-11-11 10:57 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  border-radius: 4px;
удалила

2021-11-11 18:57 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  padding: 0;
сделала

2021-11-11 19:02 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  background-size: 18px 17px;
огонь!круто получилось!

2021-11-11 19:03 UTC, DaryaNikolaeva31 commented on css/styles.css
> +.button-booking:hover {
да, работает

2021-11-11 19:10 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  transform: matrix(-1, 0, 0, 1, 0, 0);
и правда...я почему-то подумала, что здесь обязательно должно быть чтото хитро придуманное
исправила

2021-11-11 19:39 UTC, DaryaNikolaeva31 commented on css/styles.css
> +.field:invalid {
ааа, как же круто! мне правда потребовалось раза 3 прочитать и минут 15 переварить, но я поняла!

2021-11-11 19:41 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  outline: 2px solid #ff5757;
focus 3px
остальные по 2px

2021-11-11 19:44 UTC, DaryaNikolaeva31 commented on css/styles.css
> +}
добавила border: none;
вроде сработало
так можно же?

2021-11-11 22:03 UTC, DaryaNikolaeva31 commented on css/styles.css
> +}
заменила на offset!

2021-11-12 17:57 UTC, wrgraff commented on index.html
> +        <img class="main-screen-picture-end" src="img/divider.svg">
Псевдоэлементом тоже хорошо )

2021-11-12 17:58 UTC, wrgraff commented on catalog.html
> +                </svg>
Можно убрать их в фон иконки или псевдоэлемента )

2021-11-12 18:08 UTC, wrgraff commented on css/styles.css
> +  font-family: PT Sans;
А где кавычки и начертание? О_о
Можно кстати поступить проще, заставив элемент наследовать шрифт:
```suggestion
  font-family: inherit;
```

2021-11-12 18:08 UTC, wrgraff commented on css/styles.css
> +  border-radius: 10px 0px 0px 10px;
Мы по кодгайду нулевые значение пишем без единиц измерения
```suggestion
  border-radius: 10px 0 0 10px;
```

2021-11-12 18:08 UTC, wrgraff commented on css/styles.css
> +  outline: 2px solid #ff5757;
а, оке )

2021-11-12 18:09 UTC, wrgraff commented on css/styles.css
> +.field:invalid {
А чего не поправила? )

2021-11-12 18:09 UTC, wrgraff commented on css/styles.css
> +.field:invalid {
Ааа, вижу

2021-11-12 18:12 UTC, wrgraff commented on css/styles.css
> +.field:invalid:placeholder-shown {
Еще можно было не скидывать, а использовать `:not(:placeholder-shown)`.
Так можно сразу выбрать заполненный инпут )

2021-11-12 18:12 UTC, wrgraff commented on css/styles.css
> +}
Я бы наоборот бордером тут обошелся, потому что он как бы уже есть и сдвигать ничего не будет )

2021-11-12 18:13 UTC, wrgraff approved these changes

2021-11-12 18:14 UTC, merged

2021-11-12 21:10 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  font-family: PT Sans;
уже поправила)

2021-11-12 21:10 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  border-radius: 10px 0px 0px 10px;
дада, помню, опять тупо скопировала фигму(
исправляю!