7Декоративные элементы на внутренней странице
htmlacademy-htmlcss/142152-sedona-32 pull request #11
Opened 2021-11-12 22:08 UTC by DaryaNikolaeva31

1. На странице каталога не получается сделать границу у блока "Подпишитесь на рассылку" и состояния тоже не работают-должен меняться фон 
2. Не получается в футере менять цвет логотипа разработчика на состояниях, пробовала fill-не выходит
3. На главной в блоке "подпишитесь на рассылку" появилась в фоне полоса, когда и откуда не понимаю, не срабатывает ховер на поле email(не меняется фон)
4. На главной перестали срабатывать состояния на соцсетях, я вроде все так как ты говорил сделала...немного уже запуталась в каскадировании, наследовании и браузерных стилях по умолчанию-вероятно тут все сразу

Вопросы:

- не понимаю, как впихнуть от/до в ячейки в фильтре каталога в блоке стоимости
- не понимаю, как правильно прописать состояния для чекбокса с псевдоэлементами-получается длинный селектор
- не понимаю, как в попапе прописать состояния для картинки, заголовка и текста-ведь только для ссылок можно(текст без ссылки)
- в попапе вокруг ссылки "все избранное"-белая граница-что это и откуда и как от этого избавиться

2021-11-12 23:35 UTC, wrgraff requested changes
1. У тебя `.field:invalid:placeholder-shown` и `.field:invalid` переписывают все стили других состояний.
  И тут момент в том, что надо попробовать использовать `:not(:placeholder-shown)`, чтобы эти классы не срабатывали для фокусного состояния вообще.
2. Потому что он подключен как `<img>`, а цвет можно менять только инлайновому `<svg>`
3. Блок у тебя на 10 пикселей выше. Отсюда и полоса. Кстати, чтобы такое не происходило — стоит использовать размер фона `cover`
4. Для `.footer-social-icon` задан цвет, он перебивает наследуемый цвет от ссылки.

2021-11-12 23:42 UTC, wrgraff commented
> не понимаю, как впихнуть от/до в ячейки в фильтре каталога в блоке стоимости

Или обернуть и поставить абсолютом, или рамки рисовать для `.catalog-filter-label`, а не инпутов. Скорее первое, со вторым могут быть проблемы из-за стайлгайда

> не понимаю, как правильно прописать состояния для чекбокса с псевдоэлементами-получается длинный селектор

А какой длинный? `.control-input:checked + control-label::before` — вроде обычный )

> не понимаю, как в попапе прописать состояния для картинки, заголовка и текста-ведь только для ссылок можно(текст без ссылки)

А ты заверни их в одну ссылку общую )
Есть и другие методы, но мудрить сейчас не хочется

2021-11-13 00:43 UTC, wrgraff commented on index.html
> +                    <svg class="cart-remove-icon" width="16" height="16" viewBox="0 0 16 16" fill="none">
Ну вот тут инлайном не обязательно )

2021-11-13 00:43 UTC, wrgraff commented on css/styles.css
> +  font-family: "PT Sans", sans-serif;
а это зачем )

2021-11-13 00:43 UTC, wrgraff commented on css/styles.css
> +  min-height: 232px;
Вот эта штука создает тебе полосу внизу, потому что контент по высоте на пиксель меньше )

2021-11-13 00:43 UTC, wrgraff commented on css/styles.css
> +  border: 1px solid #e6e6e6;
А рамка создает отступы вокруг кнопки

2021-11-13 00:43 UTC, wrgraff commented on css/styles.css
> +  margin-left: 17px;
Отступы лучше делать между элементами, а не теми элементами, что лежат внутри )
Например, тут заголовок лежит внутри `.cart-title-link`, который уже взаимодействует с другими элементами

2021-11-13 00:43 UTC, wrgraff commented on css/styles.css
> +.miniblock {
странное название )

2021-11-13 00:43 UTC, wrgraff commented on css/styles.css
> +  margin-left: 17px;
А почему не gap?

2021-11-13 09:50 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  margin-left: 17px;
gap сделает отступы между всеми колонками, а мне нужно только тут

2021-11-13 09:56 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  min-height: 232px;
убрала

2021-11-13 09:58 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  border: 1px solid #e6e6e6;
рамку я не могу убрать-она же нужна для всего попапа
я попробовала обнулить бордер и аутлайн у кнопки-не помогло

2021-11-13 10:21 UTC, DaryaNikolaeva31 commented
> 1. :not(:placeholder-shown)

c первым пунктом :not(:placeholder-shown) не выходит(

2021-11-13 10:22 UTC, DaryaNikolaeva31 commented on index.html
> +                    <svg class="cart-remove-icon" width="16" height="16" viewBox="0 0 16 16" fill="none">
ок
просто решила раз так везде сделала, пусть одинаково будет

2021-11-13 10:23 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  font-family: "PT Sans", sans-serif;
удалила

2021-11-13 10:30 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  margin-left: 17px;
переделала, спасибо!

2021-11-13 10:30 UTC, DaryaNikolaeva31 commented on css/styles.css
> +.miniblock {
ну у меня в карточке товара так же, решила не переделывать, чтобы было в одном стиле

2021-11-13 21:32 UTC, wrgraff commented on css/styles.css
> +  outline: 1px solid #e6e6e6;
Не рисуй аутлайном декор, оставь его для фокусировок.
Тем более, это проблему то не решает. Рамочка внутри или снаружи — все равно видимая рамочка.
Можно использовать бордер, а кнопке дать отрицательные отступы по 1px со сторон, где ей надо бордер перекрыть

2021-11-13 21:32 UTC, wrgraff commented on css/styles.css
> +  border: 1px solid #e6e6e6;
Ну кнопка то не виновата, что вокруг инпуте рамка. Зачем ей что-то обнулять, если это не ее рамка

2021-11-13 21:33 UTC, wrgraff commented on css/styles.css
> +  margin-left: 17px;
А почему ты думаешь, что нужен только тут?
Если он будет ещё и между кнопкой и текстом в средней колонке — чем плохо?
Лишняя гарантия, что контент не "слипнется"

2021-11-14 21:24 UTC, wrgraff approved these changes

2021-11-14 21:24 UTC, wrgraff commented on css/styles.css
> +  font-family: "PT Sans", sans-serif;
У нас не Барбершоп, шрифт у нас совпадает у всех текстов

2021-11-14 21:24 UTC, merged