Завершение вёрстки всех компонентов
htmlacademy-htmlcss/142152-sedona-32 pull request #12
Opened 2021-11-15 20:23 UTC by DaryaNikolaeva31

2021-11-15 21:44 UTC, wrgraff requested changes
Там в общем то сетку я в ролике разобрал неплохо )

2021-11-15 21:44 UTC, wrgraff commented on index.html
>        </section>
Непонятно как заголовок остался в секции совсем один )
Какая-то странная секция

2021-11-15 21:44 UTC, wrgraff commented on index.html
> +            placeholder="01.01.2020" value="1 сентября 2021">
Судя по стайлгайду, плейсхолдер там вот такой:
<img width="611" alt="изображение" src="https://user-images.githubusercontent.com/37917037/141857704-09effdae-ab5f-4634-9133-c9e1249725fb.png">

2021-11-15 21:44 UTC, wrgraff commented on index.html
> +        <div class="field-group quantity-people quantity-children">
Если что, этот див не закрыт (в ролике увидишь)

2021-11-16 21:27 UTC, DaryaNikolaeva31 commented on index.html
>        </section>
убрала
из лайва копировала, будь они не ладны)

2021-11-16 21:27 UTC, DaryaNikolaeva31 commented on index.html
> +            placeholder="01.01.2020" value="1 сентября 2021">
заменила

2021-11-16 21:28 UTC, DaryaNikolaeva31 commented on index.html
> +        <div class="field-group quantity-people quantity-children">
закрыла, спасибо!

2021-11-17 15:53 UTC, wrgraff commented on index.html
>        </section>
В лайве в секции вся форма, она добавляется в нее, а не после нее

2021-11-17 22:33 UTC, merged