Разметка главной страницы
htmlacademy-htmlcss/142152-sedona-32 pull request #2
Opened 2021-09-26 12:37 UTC by DaryaNikolaeva31

2021-09-26 17:17 UTC, wrgraff requested changes
Для первой работы очень хорошо!

Хорошо соблюдаешь пространство имен.
Но немного кажется местами перемудрила, можно чуууууть-чуть попроще быть =)

2021-09-26 17:17 UTC, wrgraff commented on index.html
> +        <button class="button booking" type="submit">ПОИСК ГОСТИНИЦЫ В седоне</button>
А что с регистром тут случилось?
Вообще, мы все пишем в самом обычном регистре, а если нужно сделать иначе, то это будет сделано через стили

2021-09-26 17:17 UTC, wrgraff commented on index.html
> +        <button class="button booking" type="submit">ПОИСК ГОСТИНИЦЫ В седоне</button>
Если у нас есть страница отдельная с поиском, то мы можем сделать не кнопку, а ссылку на такую страницу (а раз мы не знаем, есть ли, то давай представим идеальный вариант, в котором страница такая есть).
Таким образом, если JS не сработает по какой-то причине, то вместо окошка поверх страницы пользователь перейдет на отдельную страницу и сможет воспользоваться поиском там (в противоположном случае он поиском воспользоваться не сможет)

2021-09-26 17:17 UTC, wrgraff commented on index.html
> +        <ul class="advantages-list">
Тут пункты прям пронумерованы, можно поэтому использовать `<ol>` =)

2021-09-26 17:17 UTC, wrgraff commented on index.html
> +            <span class="visually-hidden">Подписаться</span>
В этой кнопке текст вполне себе видимый, поэтому не нужно его прятать

2021-09-26 17:17 UTC, wrgraff commented on index.html
> +            <input class="field"  placeholder="Ваш Email" type="email" name="subscribe-email" id="subscribe-email" required>
Повнимательнее с текстом, он должен соответствовать макету

```suggestion
            <input class="field" placeholder="Ваш e-mail" type="email" name="subscribe-email" id="subscribe-email" required>
```

2021-09-26 17:17 UTC, wrgraff commented on index.html
> +          <p class="subscribe-email">
Учитывая, что тут всего одно поле и кнопка, можно и без параграфа бы обойтись

2021-09-26 17:17 UTC, wrgraff commented on index.html
> +      </section>
Ради одной ссылки заводить целый `<section>` это немного перегиб =)

2021-09-26 17:17 UTC, wrgraff commented on index.html
> +        </a>
Вот тут для незрячего можно добавить немного скрытого текста, чтобы он понял, что это именно разработчик сайта.
Ну или в тот же заголовок можно добавить, если оставишь его

2021-09-26 17:17 UTC, wrgraff commented on index.html
> +            <a class="button" href="https://twitter.com/htmlacademy_ru">
А почему класс `button`?
Все-таки, эти ссылки не выглядят как кнопки, поэтому не очень логично их объединять в общий класс

2021-09-27 10:25 UTC, DaryaNikolaeva31 commented on index.html
> +    <meta name="" content="">
удалила

2021-09-27 10:26 UTC, DaryaNikolaeva31 commented on index.html
> +    <base href="https://www.htmlacademy-assets.com/assets/">
удалила

2021-09-27 10:27 UTC, DaryaNikolaeva31 commented on index.html
> +    <link rel="stylesheet" href="style.css">
удалила

2021-09-27 10:28 UTC, DaryaNikolaeva31 commented on index.html
> +<!--- прописать правильный адрес для base и favicon, уточнить формат  -->
в стайлгайде лежит фавиконка, я подумала, что надо добавить
но давай уберу пока, можно же будет добавить позже

2021-09-27 10:30 UTC, DaryaNikolaeva31 commented on index.html
> +      <!-- Шапка сайта -->
удалила

2021-09-27 10:31 UTC, DaryaNikolaeva31 commented on index.html
> +            <input class="field"  placeholder="Ваш Email" type="email" name="subscribe-email" id="subscribe-email" required>
исправила

2021-09-27 10:37 UTC, DaryaNikolaeva31 commented on index.html
> +          <p class="subscribe-email">
а что использовать вместо параграфа? <span>?

Вопрос: 
Разве я не должна думать "на будущее", на случай, если изменят текст, например он станет больше или появится вторая кнопка?-это уточняющий вопрос, в смысле, что я не спорю, а спрашиваю, необходимо ли мне думать, как в будущем может измениться макет и стараться предуагадать?
я ранее работала менеджером проектов, и часто, после выкатки проекта заказчик менял тексты, добавлял отступы и тд, и от того, что никто из команды не подумал об этом, ни дизайнер, ни верстальщик, некоторые вещи приходилось переверстывать, что сильно тормозило общий процесс

2021-09-27 10:41 UTC, DaryaNikolaeva31 commented on index.html
> +      </section>
удалила section, добавила span
мне показалось, что там 4 блока, ведь вместо ссылки разработчика, заказчик может добавить что-то другое, например кнопки поделиться, но это также к вопросу выше относится

2021-09-27 10:41 UTC, DaryaNikolaeva31 commented on index.html
> +        </a>
добавила в заголовок

2021-09-27 10:44 UTC, DaryaNikolaeva31 commented on index.html
> +            <a class="button" href="https://twitter.com/htmlacademy_ru">
и правда, лошара я, копировала из лайва
поменяла класс на footer-social-link

2021-09-27 10:45 UTC, DaryaNikolaeva31 commented on index.html
> +        <!--прописать правильный адрес для лого и уточнить размеры-->
я потому и добавила комментарий "переделать адрес для лого"
но ок, удалю, ты прав, в задании четко указано

2021-09-27 10:46 UTC, wrgraff commented on index.html
> +<!--- прописать правильный адрес для base и favicon, уточнить формат  -->
Да, но пока ведь она не выведена в картинку.
Вы этим на графике заниматься будете: экспорту учиться, и прочее. Пока из тех ресурсов, что мы добавляем, хотя их пока и нет, у нас только контентные картинки

2021-09-27 10:46 UTC, wrgraff commented on index.html
> +        <!--прописать правильный адрес для лого и уточнить размеры-->
Тут всем картинкам адреса менять надо будет =)

2021-09-27 10:48 UTC, DaryaNikolaeva31 commented on index.html
> +            <a class="navigation-link" href="#"><span class="visually hidden">Добавить в Избранное</span></a>
исправила

2021-09-27 10:48 UTC, DaryaNikolaeva31 commented on index.html
> +            <a class="navigation-link" href="#"><span class="visually hidden">Поиск</span></a>
исправила, стыдно ужасно(

2021-09-27 10:49 UTC, DaryaNikolaeva31 commented on index.html
> +            <a class="navigation-link" href="index.html">Главная</a>
исправила, спасибо!

2021-09-27 10:51 UTC, DaryaNikolaeva31 commented on index.html
> +            <a class="navigation-link" href="about-us.html">О Седоне</a>
исправила

2021-09-27 10:52 UTC, DaryaNikolaeva31 commented on index.html
> +        <!--изменить адреса ссылок-->
ок, комментарий удалила, вторая страница, помимо главной, Гостиницы же? у нее адрес оставила, остальные заглушки

2021-09-27 10:54 UTC, wrgraff commented on index.html
> +          <p class="subscribe-email">
Да, должны продумывать наперед, но не везде.
Например, если у нас на странице список чего-либо (преимуществ, например), то мы должны учитывать, что их может стать больше или меньше.

Предугадывать добавление новых кнопок не стоит, так как это ведет к изменениям дизайна, а их правильно предугадать невозможно. Поэтому, стараемся верстать максимально гибко, чтобы эти изменения проще внедрялись. Добавление отступов и изменение текстов не должно приводить к большим проблемам.

> а что использовать вместо параграфа? ?

Ничего, достаточно будет самой формы. Параграф в данном случае просто оборачивает все, что внутри формы. Других полей в форме подписки не предвидится.
Если бы там было несколько полей, то параграфы бы оборачивали каждый свое поле, а их всех оборачивала бы форма. Но тут не так

2021-09-27 10:58 UTC, DaryaNikolaeva31 commented on index.html
> +      <h1>Седона — небольшой городок в Аризоне, заслуживающий большего!</h1>
исправила

2021-09-27 11:00 UTC, wrgraff commented on index.html
> +      </section>
Лучше бы наверное `<div>`, он по поведению как `<section>`, но избавит от необходимости делать заголовок для одной ссылки.

Допустим, добавит кнопки поделиться.
Это совсем другой блок будет, его можно будет оформить хоть в `<section>`, хоть во что-то еще.
Можно добавить не только вместо, но и до и после.
Не совсем понятно, как именно это влияет на отдельно взятый блок со ссылкой на разработчика.

Может туда добавят вообще меню в футер. Или полезные ссылки. Это все довольно глобальные изменения, которые все равно потребуют работы руками

2021-09-27 11:01 UTC, DaryaNikolaeva31 commented on index.html
> +      </section>
исправила

2021-09-27 11:04 UTC, DaryaNikolaeva31 commented on index.html
> +        <button class="button booking" type="submit">ПОИСК ГОСТИНИЦЫ В седоне</button>
исправила
заменила кнопку на ссылку

2021-09-27 11:05 UTC, DaryaNikolaeva31 commented on index.html
> +        <ul class="advantages-list">
исправила

2021-09-27 11:06 UTC, wrgraff commented on index.html
> +            <a class="button" href="https://twitter.com/htmlacademy_ru">
А там как раз у них ссылки на соцсети на кнопки похожи =)

2021-09-27 18:56 UTC, wrgraff commented on index.html
> +              <span class="visually-hidden">Список Избранного</span>
Почему с большой буквы )

2021-09-27 18:56 UTC, wrgraff commented on index.html
> +            <a class="navigation-link" href="#"><span class="visually hidden">Поиск</span></a>
Да ну брось, ошибаться это нормально.
Все мы не без греха =)

2021-09-27 18:57 UTC, wrgraff commented on index.html
> +        <!--изменить адреса ссылок-->
Да, все так )

2021-09-27 19:09 UTC, wrgraff requested changes
Все-таки нужна еще небольшая доработка, чтобы код был валидным

2021-09-27 19:09 UTC, wrgraff commented on index.html
> +                <h3 class="services-title">Жильё</h3>
Только теперь эти заголовки подчиняются пункту "Настоящий городок", а значит должны быть на один уровень больше него.

https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/151ce7dec06fbde164819e3e7456961845978cd1/index.html#L54

https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/151ce7dec06fbde164819e3e7456961845978cd1/index.html#L58

https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/151ce7dec06fbde164819e3e7456961845978cd1/index.html#L62

2021-09-27 19:09 UTC, wrgraff commented on index.html
> +            <span class="subscribe-button">Подписаться</span>
`subscribe-button` повторяет класс на самой кнопке.
На самом деле, `<span>` то тут и не нужен, ведь достаточно и саму кнопку стилизовать

2021-09-27 19:09 UTC, wrgraff commented on index.html
> +        <h2 class="visually-hidden">Разработчик сайта - HTML Academy</h2>
Увы, но получился невалидный код, [`<h2>` нельзя вкладывать в `<span>`](https://caninclude.glitch.me/can/include/?child=h2&parent=span) =(

2021-09-28 09:39 UTC, DaryaNikolaeva31 commented on index.html
> +          <p class="subscribe-email">
удалила тег p

2021-09-28 09:42 UTC, DaryaNikolaeva31 commented on index.html
> +              <span class="visually-hidden">Список Избранного</span>
исправила Избранное

2021-09-28 09:43 UTC, DaryaNikolaeva31 commented on index.html
> +                <h3 class="services-title">Жильё</h3>
поняла, исправила
невнимательность(

2021-09-28 10:02 UTC, DaryaNikolaeva31 commented on index.html
> +            <span class="subscribe-button">Подписаться</span>
исправила

2021-09-28 10:05 UTC, DaryaNikolaeva31 commented on index.html
> +        <h2 class="visually-hidden">Разработчик сайта - HTML Academy</h2>
заменила span на p
или лучше div?

2021-09-28 16:16 UTC, wrgraff commented on index.html
> +        <h2 class="visually-hidden">Разработчик сайта - HTML Academy</h2>
А вот прошла бы по ссылочке и проверила: [можно ли вложить `<h2>` в `<p>`](https://caninclude.glitch.me/can/include/?child=h2&parent=p)?
Увы =(

2021-09-28 20:38 UTC, wrgraff approved these changes

2021-09-28 20:38 UTC, merged