Разметка внутренней страницы
htmlacademy-htmlcss/142152-sedona-32 pull request #3
Opened 2021-09-29 11:30 UTC by DaryaNikolaeva31

2021-09-30 00:25 UTC, wrgraff requested changes

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +    <main class="main-inner">
Лучше не задавать настолько глобальные разные классы страницам.
Страницы состоят из трех одинаковых блоков: хэдер, мэин и футер. И у них разное содержание может быть, но блоки по сути одинаковы

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +        <h1 class="inner-header-title">Гостиницы Седоны</h1>
Используй просто header-title. На главной такого нет, а значит это единственный хэдер тайтл )
Ну и сам `<header>` странновато называть внутренним, если это хэдер блока `<main>`.

Понимаю, что это решения из демо-проекта, но там как-то много странных решений в этот раз =(

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +        <h2 class="visually-hidden">Список гостиниц с фильтрами</h2>
Насколько вижу, в этом секшене — только фильтры, никаких гостиниц нет, они в своем секшене

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +                  <span class="control-mark"></span>
На самом деле, можно вполне без этих спанов сверстать.
Вам что-то уж больно упрощенный вариант стали давать (при том, что сложный даже и не особо сложнее).

https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/1b2bbe8f570e896d4c8ae3663f2dc91ab45996d6/catalog.html#L61
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/1b2bbe8f570e896d4c8ae3663f2dc91ab45996d6/catalog.html#L74
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/1b2bbe8f570e896d4c8ae3663f2dc91ab45996d6/catalog.html#L84
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/1b2bbe8f570e896d4c8ae3663f2dc91ab45996d6/catalog.html#L91
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/1b2bbe8f570e896d4c8ae3663f2dc91ab45996d6/catalog.html#L98

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +                  <span class="control-label">Парковка</span>
А тут забыла про `control-mark`.
По мне так лучше бы везде так =)

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +            </table>
Ой, нет, какая же это таблица?
Таблица — для табличных данных. А тут так стилизованы поля ввода

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +            <input type="reset" value="Сбросить">
Такие кнопки сейчас делаются тегом `<button>`, инпуты для кнопок считаются устаревшими (а еще их сложнее стилизовать)

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +            <button class="visually-hidden" type="submit">Отсортировать продукты</button>
Непонятно, а эта кнопка как работать будет, если она скрыта?
Мы вот на нее нажать не сможем. Сможем сфокусироваться, но не увидим на чем мы сфокусировались.

Кажется, в этом случае можно и без кнопки обойтись
(да, знаю, что в демо кнопка, но это прям странное решение)

Еще один случай:
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/1b2bbe8f570e896d4c8ae3663f2dc91ab45996d6/catalog.html#L283

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +          </ul>
Эх, а еще задать бы кнопкам один общий класс (для общих стилей вроде размеров и рамки) и один дополнительный для стилизации иконки в этих кнопках.

Просто так хорошо размечены, что у меня максимализм включился сразу =)

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +              </table>
Ой, нет, опять таблица!
Таблицы для расположения элементов мы не используем. Это делали 10 лет назад, когда не было совсем никаких возможностей нормальных.
Сейчас мы используем таблицы для табличных данных.

Вроде таких:
![изображение](https://user-images.githubusercontent.com/37917037/135365550-0598092f-2838-47b8-b7a0-b4ab30396a26.png)

А еще мощнее таблицы двумерные, вроде такой:
![изображение](https://user-images.githubusercontent.com/37917037/135365698-66790804-6384-4d71-9070-9581afc8fbef.png)

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +              </div>
Незрячему человеку скринридер зачитает примерно следующее:

> Список. 4 пункта: картинка, картинка, картинка, картинка

(зачитались бы alt'ы, но их нет)

А что мы вообще-то хотим донести?
Что это _четырехзвездная гостиница_. А количество иконок — это лишь графический эквивалент этой информации.

Подойти стоит к этому как к разметке интерактивных элементов с графикой, но без текста. Как иконки соцсетей. Только тут элемент не интерактивный

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +              <a class="pagination-link" href="#">...</a>
Для незрячего не очень понятно, что обозначает это многоточие.
Хорошо бы доступность улучшить

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +        <section class="pagination">
Непонятно, почему пагинация в отдельный секшн попала. Она без списка, который "пагинирует" особо смысла не имеет )
Да и заголовка нет у секшена (ну, потому что он и не нужен же тут)

2021-09-30 00:25 UTC, wrgraff commented on catalog.html
> +    </main>
Что-то случилось с форматированием, где-то перекос или закрывающий тег потерялся

2021-09-30 10:48 UTC, DaryaNikolaeva31 commented on catalog.html
> +    <main class="main-inner">
исправила

2021-09-30 10:55 UTC, DaryaNikolaeva31 commented on catalog.html
> +        <h1 class="inner-header-title">Гостиницы Седоны</h1>
исправила

2021-09-30 10:59 UTC, DaryaNikolaeva31 commented on catalog.html
> +        <h2 class="visually-hidden">Список гостиниц с фильтрами</h2>
поменяла на "Фильтры для выбора гостиницы"

2021-09-30 11:05 UTC, DaryaNikolaeva31 commented on catalog.html
> +                  <span class="control-mark"></span>
удалила

2021-09-30 11:06 UTC, DaryaNikolaeva31 commented on catalog.html
> +                  <span class="control-label">Парковка</span>
)))))))удалила везде

2021-09-30 11:17 UTC, DaryaNikolaeva31 commented on catalog.html
> +            </table>
ок, исправила на input type="text"
*подумала, что раз всего два поля, можно таблицей)

2021-09-30 11:24 UTC, DaryaNikolaeva31 commented on catalog.html
> +            <input type="reset" value="Сбросить">
на инпуты для кнопок много тренажеров, думала козырну и ты меня похвалишь))))))

2021-09-30 11:24 UTC, DaryaNikolaeva31 commented on catalog.html
> +            <input type="reset" value="Сбросить">
передела на button(

2021-09-30 11:33 UTC, DaryaNikolaeva31 commented on catalog.html
> +            <button class="visually-hidden" type="submit">Отсортировать продукты</button>
удалила обе кнопки

2021-09-30 11:34 UTC, DaryaNikolaeva31 commented on catalog.html
> +          </ul>
подожди, это же не кнопки, а ссылки?

2021-09-30 11:48 UTC, DaryaNikolaeva31 commented on catalog.html
> +          </ul>
добавила 
<a href="#" class="button-list **show-cards show-type**">

2021-09-30 12:08 UTC, DaryaNikolaeva31 commented on catalog.html
> +              </table>
заменила на <p class="miniblock-left">Мотель</p>
              <p class="miniblock-right">От 3000 ₽</p>

2021-09-30 20:44 UTC, DaryaNikolaeva31 commented on catalog.html
> +        <section class="pagination">
заменила на div
без заголовка

2021-10-01 12:00 UTC, DaryaNikolaeva31 commented on catalog.html
> +    </main>
вроде поправила

2021-10-01 12:01 UTC, DaryaNikolaeva31 commented on catalog.html
> +              <a class="pagination-link" href="#">...</a>
поставила скрытый текст <li class="pagination-item visually-hidden">Переход на 5 страницу
правда не уверена, что правильно

2021-10-02 09:52 UTC, DaryaNikolaeva31 commented on catalog.html
> +              </div>
исправила

2021-10-02 10:21 UTC, wrgraff commented on catalog.html
> +            <input type="reset" value="Сбросить">
Мы как раз с коллегой обсуждали откуда инпуты эти берутся, ведь вроде бы метод старый и не должны были ему учить ))

2021-10-02 10:24 UTC, wrgraff commented on catalog.html
> +    </main>
Кажется нет =(

2021-10-02 11:00 UTC, wrgraff requested changes

2021-10-02 19:18 UTC, DaryaNikolaeva31 commented on catalog.html
> +    </main>
вот теперь точно!после твоего видоса)

2021-10-02 19:19 UTC, DaryaNikolaeva31 commented on catalog.html
>            <form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get">
исправила

2021-10-02 19:22 UTC, DaryaNikolaeva31 commented on catalog.html
> +            </label>
поменяла местами)

2021-10-02 19:27 UTC, DaryaNikolaeva31 commented on catalog.html
> +              <a href="#" class="button-cards show-cards show-type">
исправила

2021-10-02 19:34 UTC, DaryaNikolaeva31 commented on catalog.html
> +                <p class="visually-hidden rating-stars">Гостиница 4 звезды</p>
исправила

2021-10-03 09:32 UTC, DaryaNikolaeva31 commented on catalog.html
> +            <li class="pagination-item visually-hidden">Переход на 5 страницу
добавила в ссылку спан

2021-10-03 09:45 UTC, wrgraff approved these changes

2021-10-03 09:45 UTC, wrgraff commented on catalog.html
> +          <a href="#" class="button-cards-grid">
Не очень внимательно пример посмотрела. Ничего, стилизовать начнем — появится визуальное подкрепление и станет понятно зачем и что.

```suggestion
          <a href="#" class="button-cards button-cards-grid">
```

2021-10-03 09:45 UTC, wrgraff commented on catalog.html
> +          </a>
Лучше не комбинировать содержание то на той же строке, то на отдельных.
Я на отдельных предпочитаю:

```suggestion
          <a class="pagination-link" href="#">
            ...
            <span class="visually-hidden">Переход на 5 страницу</span>
          </a>
```

2021-10-03 09:45 UTC, merged

2021-10-03 15:32 UTC, DaryaNikolaeva31 commented on catalog.html
> +          <a href="#" class="button-cards-grid">
исправила

2021-10-03 15:33 UTC, DaryaNikolaeva31 commented on catalog.html
> +          </a>
исправила