Графика для всех страниц
htmlacademy-htmlcss/142152-sedona-32 pull request #4
Opened 2021-10-03 10:41 UTC by DaryaNikolaeva31

2021-10-04 17:44 UTC, wrgraff requested changes

2021-10-04 17:44 UTC, wrgraff commented on catalog.html
> +            <img src="img/search.svg"  width="18" height="18" alt="Поиск">
Если бы у нас не хватало контентых картинок — я бы сказал.

Было правильно, что эти картинки не находились в разметке, так как в разметку мы ставим только те картинки, которые несут новую информацию.
Иконка поиска не несет никакой информации, это просто индикатор, графика.
Хорошие примеры контентных картинок:
- логотип: это логотип конкретной компании, фирменный знак, он важен и на нем узнаваемое изображение бренда
- изображение товара на карточке товара: это фото именно того товара, который представляет карточка
- скриншот экрана программы: представляет интерфейс именно той программы, которую мы продаем/показываем пользователю.
Ну и так далее

В самом задании, кстати, отмечено, что иконки сейчас можно не подключать:
> достаточно подключить несколько крупных фоновых изображений или текстур, мелкие иконки можно не подключать.

Все эти картинки в разметке были не нужны:
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/catalog.html#L31
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/catalog.html#L37
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/catalog.html#L53
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/catalog.html#L56
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/catalog.html#L132
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/catalog.html#L138
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/catalog.html#L144
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/catalog.html#L265
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/catalog.html#L271
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/catalog.html#L277
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/index.html#L31
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/index.html#L37
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/index.html#L60
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/index.html#L65
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/index.html#L70
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/index.html#L122
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/index.html#L128
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/index.html#L134

2021-10-04 17:44 UTC, wrgraff commented on css/styles.css
> +  background: #ffffff;
Лучше при указании цвета использовать `background-color`, а то привычка может привести к тому, что когда из всех свойств фона ты попытаешься сменить только цвет, то напишешь `background` и обнулишь им позиционирование, повторение, размер и изображение.

https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/css/styles.css#L21
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/css/styles.css#L36

2021-10-04 17:44 UTC, wrgraff commented on css/styles.css
> +  background-image: url("../img/catalog-background.png");
Изображение показывается, но только не то изображение и не в том месте )

В футере другая размытая картинка в блоке подписки:
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/css/styles.css#L58

В каталоге фон на самом деле не на `<main>` (тем более это и главную затронет), а на заголовке и фильтре.
https://github.com/htmlacademy-htmlcss/142152-sedona-32/blob/5d5f2a6a5acac1ece0ec34306acf7ebbd132165d/css/styles.css#L62

2021-10-04 17:44 UTC, wrgraff commented on css/styles.css
> +  background-image: url("../img/catalog-background.png");
Забыла, что нужно обязательно поставить фоновый цвет по критерию [ALLY-05](https://up.htmlacademy.ru/htmlcss/32/criteries#ALLY-05)

Конечно, и цвет текста тоже стоит поменять, чтобы он как и в макете был заметен на фоне картинки (или цвета).

2021-10-05 09:46 UTC, DaryaNikolaeva31 commented on catalog.html
> +            <img src="img/search.svg"  width="18" height="18" alt="Поиск">
удалила

2021-10-05 09:49 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  background: #ffffff;
исправила
Коля на лайве просто говорил, берем и копируем из фигмы не думая)ну я не подумала, хотя полностью с тобой согласна)

2021-10-05 09:51 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  background-image: url("../img/catalog-background.png");
поправила

2021-10-05 10:02 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  background-image: url("../img/catalog-background.png");
завернула заголовок и фильтр в div

2021-10-05 22:05 UTC, wrgraff commented on css/styles.css
> +  background: #ffffff;
Как по мне так наоборот из Фигмы почти ничего не стоит копировать, потому что стили она генерирует совсем неудачные

2021-10-06 10:10 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  background-repeat: no-repeat;
удалила

2021-10-06 11:46 UTC, wrgraff approved these changes

2021-10-06 11:46 UTC, merged