Сетка страницы и крупных блоков на флексах для главной страницы
htmlacademy-htmlcss/142152-sedona-32 pull request #6
Opened 2021-10-11 22:04 UTC by DaryaNikolaeva31

---
:mortar_board: [Сетка страницы и крупных блоков на флексах для главной страницы](https://up.htmlacademy.ru/htmlcss/32/user/142152/tasks/7)

:boom: https://htmlacademy-htmlcss.github.io/142152-sedona-32/6/

2021-10-12 17:39 UTC, wrgraff commented on index.html
> +    <div class="page-container">
Лишний контейнер

2021-10-12 17:40 UTC, wrgraff commented on index.html
> +        <img src="img/welcome.png">
Формат должен быть svg

2021-10-12 17:51 UTC, wrgraff commented on css/styles.css
> +  padding-left: 71px;
Переместить отступы на уровень выше

2021-10-12 19:43 UTC, DaryaNikolaeva31 commented on index.html
> +        <img src="img/welcome.png">
исправила

2021-10-13 01:24 UTC, wrgraff requested changes
То, что я упоминаю про `box-sizing`, можно более подробно посмотреть здесь [в заметке](https://frontend-design.notion.site/box-sizing-74c2b981a9624d03ba122967a529b9ad).

Основное ревью в формате видео [лежит на ютубе](https://youtu.be/dBkzReRubWc), комментарии просто обозначают какие-то моменты, которые я там обсуждаю. Смотри ролик, там подробно все описано =)

2021-10-13 21:11 UTC, wrgraff approved these changes

2021-10-13 21:11 UTC, merged