Построение мелких сеток на гридах для подходящих компонентов
htmlacademy-htmlcss/142152-sedona-32 pull request #9
Opened 2021-10-31 21:35 UTC by DaryaNikolaeva31

привет
попробовала сделать грид областями, но не выходит(
вроде тренажеры прошла по гридам, они и правда удобнее во многом

2021-11-02 16:39 UTC, wrgraff requested changes
Помимо поломок все весьма неплохо =)

2021-11-02 16:39 UTC, wrgraff commented on css/styles.css
> +  z-index: 1;
Если тебе нужно только логотип подвинуть на передний план, зачем сперва вытаскивать на передний план `.main-container`, чтобы затем логотип вытащить еще на слой выше?
Не проще ли просто вытащить вперед логотип?

2021-11-02 16:39 UTC, wrgraff commented on css/styles.css
> +  z-index: 2;
Добавь `position: relative`, без него могут быть проблемы с работой `z-index`

2021-11-02 16:39 UTC, wrgraff commented on css/styles.css
> +  padding:0;
Хорошо бы задать какие-то адекватные отступы, чтобы текст не смог примкнуть к краю элемента

2021-11-02 16:39 UTC, wrgraff commented on css/styles.css
> +  padding-right: 35px;
Если ты уже задала ширину — зачем тебе еще и отступами к ней идти?
Сглючит что-нибудь в шрифте, и он станет шире, растащит кнопку. Хотя, по прежнему мог влезать в заданный размер

2021-11-02 16:39 UTC, wrgraff commented on css/styles.css
> +  width: 1056px;
Зачем? Мы столько мучались с тем, чтобы сделать ширину сверху и не задавать ее вложенным элементам.
У тебя отступы формируют нужную ширину:
`1200 - (72 + 72) = 1056`

А теперь эта ширина наоборот все сломала, потому что работает так:
`1056 - (72 + 72) = 912`

![изображение](https://user-images.githubusercontent.com/37917037/139905356-5c14a341-77f6-4422-985e-8594135f138a.png)

2021-11-02 16:39 UTC, wrgraff commented on css/styles.css
> +}
У тебя здесь не работает именованная область, это явно видно в девтулзах:
<details>
<summary>Девтулзы</summary>

![изображение](https://user-images.githubusercontent.com/37917037/139905860-047fe345-497b-4fbe-8bd4-5db31706c406.png)

</details>

Так же это хорошо видно, если включить в инспекторе гриды и именованные области:
<details>
<summary>Разлиновка</summary>

![изображение](https://user-images.githubusercontent.com/37917037/139906304-4ba5a575-613b-4cc6-be25-f91394572bfa.png)

</details>

Заметь, не работают картинка и заголовок. У остальных все в порядке. Если эту поломку исправить, то все встанет на свои места (только отступы надо добавить):

<details>
<summary>Вот так будет если починить</summary>

![изображение](https://user-images.githubusercontent.com/37917037/139906533-8771064d-cbb1-4287-af43-31654d7302df.png)

</details>

Так почему же оно не работает?
Все просто. Ссылка конечно является прозрачной с точки зрения семантики, но не является прозрачной с точки зрения разметки. У тебя заголовок и картинка лежит в ссылке. Ссылка является грид-элементом, а картинка и заголовок — нет

2021-11-02 16:39 UTC, wrgraff commented on css/styles.css
> +  grid-area: product-title;
В остальном использование `grid-area` — это хороший выбор

2021-11-02 16:39 UTC, wrgraff commented on css/styles.css
> +}
Между кнопками вот отступ есть, а между этими блоками нет

2021-11-02 16:39 UTC, wrgraff commented on css/styles.css
> +  grid-area: button-brown;
Вот тут некоторый прокол с именованием. Потому что зеленая то кнопка в сетку не попадет уже.
Цвет это скорее состояние кнопки. А тебе надо бы привязать кнопку избранного, вне зависимости от того, зеленая она, синяя, фиолетовая или томатная (отсылочка к Вадиму Макееву)

2021-11-03 08:53 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  z-index: 1;
получается я убираю тогда z-index у main-container и оставляю z-index: 1; у логотипа

2021-11-03 08:53 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  z-index: 2;
добавила

2021-11-03 08:54 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  padding-right: 35px;
удалила

2021-11-03 08:55 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  padding:0;
так у меня нижу стоят   padding-top: 9px; padding-bottom: 10px;
этого не достаточно?

2021-11-03 08:56 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  width: 1056px;
да вообще ступила
удалила ширину!

2021-11-03 08:59 UTC, DaryaNikolaeva31 commented on css/styles.css
> +}
ооо, спасибо!так лучше видно, чем в хроме!
получается я делаю гридом еще и ссылку и тогда картинка и заголовок должны стать грид-элементами

2021-11-03 10:28 UTC, DaryaNikolaeva31 commented on css/styles.css
> +}
поставила марджин

2021-11-03 14:26 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  grid-area: button-brown;
поменяла

2021-11-03 14:27 UTC, DaryaNikolaeva31 commented on css/styles.css
> +}
вроде получилось, мне кажется чего то я лишканула в коде немного, но в целом вроде победила я этот грид!

2021-11-03 14:27 UTC, DaryaNikolaeva31 commented on css/styles.css
> +}
отдельное спасибо за скрины!

2021-11-03 19:11 UTC, wrgraff commented on css/styles.css
> +  z-index: 1;
Именно так

2021-11-03 19:12 UTC, wrgraff commented on css/styles.css
> +  padding:0;
Так ведь текст будет при увеличении количества слов в ширину сперва расти, а не в высоту =)

2021-11-03 19:14 UTC, wrgraff commented on css/styles.css
> +}
Вышло очень даже

2021-11-03 19:21 UTC, wrgraff approved these changes

2021-11-03 19:21 UTC, wrgraff commented on css/styles.css
> +  grid-template-rows: 29px 55px 37px;
```suggestion
  grid-template-rows: min-content 1fr min-content;
```

Так гибче получится. Если вдруг станет что-то выше, например, вторая строка в заголовке появится или подпись какая — сперва заберется пространство у среднего ряда, а потом уже высота элемента вырастет

2021-11-03 19:21 UTC, wrgraff commented on css/styles.css
>  }
Я бы еще `row-gap` добавил, заодно можно будет отлепить текст от заголовка

2021-11-03 19:21 UTC, wrgraff commented on catalog.html
> +            <p class="rating-text">
Вместо доп обертки попробуй прижать рейтинг вправо с помощью `justify-self`

2021-11-03 19:21 UTC, wrgraff commented on catalog.html
> +              <span class="rating-button">Рейтинг: 8,5</span>
Ну это не кнопка все-таки, странный класс )

2021-11-03 19:21 UTC, merged

2021-11-04 09:43 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  padding:0;
добавила 14пикселей

2021-11-04 09:51 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  grid-template-rows: 29px 55px 37px;
после того, как я применила предложенное тобой выше, кнопки в последней карточке изменились, не очень понимаю почему
![image](https://user-images.githubusercontent.com/89548917/140293196-4d4b5be6-37a0-45b7-909b-4976d6b74fab.png)

2021-11-04 09:57 UTC, DaryaNikolaeva31 commented on css/styles.css
>  }
добавила 4px

2021-11-04 09:59 UTC, DaryaNikolaeva31 commented on catalog.html
> +            <p class="rating-text">
я пробовала, не получилось 
и когда я начала применять стили к рейтингу, стили применялись ко всей области 520px, а мне нужен был только рейтинг, мне показалось, что обертка в спан-единственный варинат

2021-11-04 10:01 UTC, DaryaNikolaeva31 commented on catalog.html
> +              <span class="rating-button">Рейтинг: 8,5</span>
изначально я хотела дать этому рейтингу класс button, тк мне показалось, что отступы и вообще чем-то напоминал кнопку, поэтому появился rating-button следом, в процессе, я поняла, что идея неудачная и убрала button)
заменю на field)

2021-11-04 10:04 UTC, DaryaNikolaeva31 commented on css/styles.css
> +  grid-template-rows: 29px 55px 37px;
ура, сама нашла в чем косяк)